			<!-- Bottom -->
			<div id="bottom">
				<!-- wrapper-bottom -->
				<div class="wrapper">
					<div id="bottom-text">Design by <a style="color:white;" href="http://b-dev.net">BDEV</a></div>
					<!-- Social -->
					<ul class="social ">
					<!--	<li><a href="http://www.facebook.com/throwbackauthentics " class="poshytip  facebook" title="Onze faceboek pagina"></a></li>--> 
					</ul>
					<!-- ENDS Social -->
					<div id="to-top" class="poshytip" title="Boven"></div>
				</div>
				<!-- ENDS wrapper-bottom -->
			</div>
			<!-- ENDS Bottom -->
