
		
		
		<!-- CSS -->
		<link rel="stylesheet" href="http://<?=$_SERVER['HTTP_HOST']?>/css/reset.css" type="text/css" media="screen" />
		<link rel="stylesheet" href="http://<?=$_SERVER['HTTP_HOST']?>/css/style.css" type="text/css" media="screen" />
		<link rel="stylesheet" href="http://<?=$_SERVER['HTTP_HOST']?>/css/social-icons.css" type="text/css" media="screen" />
		<!--[if IE 8]>
			<link rel="stylesheet" type="text/css" media="screen" href="http://<?=$_SERVER['HTTP_HOST']?>/css/ie8-hacks.css" />
		<![endif]-->
		<!-- ENDS CSS -->	
		
		<!-- GOOGLE FONTS -->
		<link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>


		
		<!-- JS -->
		<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
		<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>

		<!-- Isotope -->
		<script src="http://<?=$_SERVER['HTTP_HOST']?>/js/isotope.pkgd.min.js"></script>
		
		<!-- jquery colorbox -->
		<link rel="stylesheet" href="http://<?=$_SERVER['HTTP_HOST']?>/css/colorbox.css">
        <script src="http://<?=$_SERVER['HTTP_HOST']?>/js/colorbox/jquery.colorbox-min.js"></script>
		
		
		<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/easing.js"></script>
		<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/jquery.scrollTo.min.js"></script>
		<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/tba/custom.js"></script>

		


		
		
		<!--[if IE]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		
		<!--[if IE 6]>
			<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/DD_belatedPNG.js"></script>
			<script>
	      		/* EXAMPLE */
	      		//DD_belatedPNG.fix('*');
	    	</script>
		<![endif]-->
		<!-- ENDS JS -->
		
		
		<!-- Nivo slider -->
		<link rel="stylesheet" href="http://<?=$_SERVER['HTTP_HOST']?>/css/nivo-slider.css" type="text/css" media="screen" />
		<script src="http://<?=$_SERVER['HTTP_HOST']?>/js/nivo-slider/jquery.nivo.slider.js" type="text/javascript"></script>
		<!-- ENDS Nivo slider -->
		
		<!-- tabs -->
		<link rel="stylesheet" href="http://<?=$_SERVER['HTTP_HOST']?>/css/tabs.css" type="text/css" media="screen" />
		<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/tabs.js"></script>
  		<!-- ENDS tabs -->

		

  		
  		<!-- prettyPhoto -->
		<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/prettyPhoto/js/jquery.prettyPhoto.js"></script>
		<link rel="stylesheet" href="http://<?=$_SERVER['HTTP_HOST']?>/js/prettyPhoto/css/prettyPhoto.css" type="text/css" media="screen" />
		<!-- ENDS prettyPhoto -->
		
		
		<!-- poshytip -->
		<link rel="stylesheet" href="http://<?=$_SERVER['HTTP_HOST']?>/js/poshytip-master/src/tip-twitter/tip-twitter.css" type="text/css" />
		<link rel="stylesheet" href="http://<?=$_SERVER['HTTP_HOST']?>/js/poshytip-master/src/tip-yellowsimple/tip-yellowsimple.css" type="text/css" />
		<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/poshytip-master/src/jquery.poshytip.min.js"></script>
		<!-- ENDS poshytip -->


		
		<!-- Fancybox -->
		
		<!-- Add mousewheel plugin (this is optional) -->
		<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/jquery.fancybox-2.1.5/lib/jquery.mousewheel-3.0.6.pack.js"></script>

		<!-- Add fancyBox -->
		<link rel="stylesheet" href="http://<?=$_SERVER['HTTP_HOST']?>/js/jquery.fancybox-2.1.5/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
		<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/jquery.fancybox-2.1.5/source/jquery.fancybox.pack.js?v=2.1.5"></script>

		<!-- Optionally add helpers - button, thumbnail and/or media -->
		<link rel="stylesheet" href="http://<?=$_SERVER['HTTP_HOST']?>/js/jquery.fancybox-2.1.5/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" type="text/css" media="screen" />
		<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/jquery.fancybox-2.1.5/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
		<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/jquery.fancybox-2.1.5/source/helpers/jquery.fancybox-media.js?v=1.0.6"></script>

		<link rel="stylesheet" href="http://<?=$_SERVER['HTTP_HOST']?>/js/jquery.fancybox-2.1.5/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" type="text/css" media="screen" />
		<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/jquery.fancybox-2.1.5/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>


		<!-- ENDS Fancybox -->

		
		<script type="text/javascript" src="http://<?=$_SERVER['HTTP_HOST']?>/js/jquery.jscroll.min.js"></script>
